"""Authentication for the HTTP transport.

Threat model
------------
The stdio transport is safe by construction: the client *is* the parent
process, and nothing else can speak to the server. The HTTP transport is not.
It binds to the loopback interface, which keeps remote machines out, but
**every local process runs as a potential client** — any script, any browser
page able to issue a cross-origin request, any other user on a shared
workstation. Since the tools read and write files on behalf of their caller,
an unauthenticated local port is a file-system capability handed to whoever
asks for it.

Two complementary answers are implemented here:

* a **shared token**, required in the ``Authorization`` header, so that a
  process which cannot read the token cannot drive the server;
* ``FMUCONTAINER_MCP_ROOT`` (see :mod:`~fmu_manipulation_toolbox.assistant.paths`),
  which limits the damage of a client that *does* hold the token.

The token is deliberately *not* generated by default for the GUI flavour:
turning on the assistant must keep working for a user who just wants to point
their IDE at the port. Authentication is opt-in, and the documentation states
plainly what is at stake.
"""

import hmac
import logging
import os
import secrets
from typing import Optional

logger = logging.getLogger("fmu_manipulation_toolbox")

#: Environment variable holding the shared token the client must present.
TOKEN_ENV_VAR = "FMUCONTAINER_MCP_TOKEN"

#: Value asking the server to make one up and print it at startup.
GENERATE = "generate"


def resolve_token() -> Optional[str]:
    """Return the token the HTTP transport requires, if any.

    ``FMUCONTAINER_MCP_TOKEN=generate`` asks for a fresh random token, which
    the caller is expected to show to the user; any other value is used as-is.
    Unset means no authentication.

    Raises:
        ValueError: If the variable is set to an empty or too short value. A
            two-character token is worse than none: it gives the illusion of
            protection.
    """
    raw = os.environ.get(TOKEN_ENV_VAR)
    if raw is None:
        return None
    if raw == GENERATE:
        return secrets.token_urlsafe(32)
    if len(raw) < 16:
        raise ValueError(
            f"{TOKEN_ENV_VAR} must be at least 16 characters long (or set to "
            f"'{GENERATE}' to let the server pick one)."
        )
    return raw


def build_auth_middleware(token: str):
    """Return an ASGI middleware rejecting requests without ``token``.

    Implemented at the ASGI level rather than with a FastMCP auth provider
    because the latter targets OAuth/JWT flows: a shared secret between two
    processes on the same machine needs none of that, and the simpler the
    check, the easier it is to audit.

    Args:
        token: The expected bearer token.

    Returns:
        An ASGI middleware factory, to wrap the MCP application with.
    """
    expected = f"Bearer {token}"

    class TokenAuthMiddleware:
        def __init__(self, app):
            self.app = app

        async def __call__(self, scope, receive, send):
            if scope["type"] != "http":
                await self.app(scope, receive, send)
                return

            headers = dict(scope.get("headers") or [])
            provided = headers.get(b"authorization", b"").decode("latin-1")

            # Constant-time comparison: a plain `==` leaks the token through
            # timing, and the attacker here is a local process able to retry
            # as often as it likes.
            if not hmac.compare_digest(provided, expected):
                logger.warning("MCP: rejected an unauthenticated HTTP request.")
                await send({
                    "type": "http.response.start",
                    "status": 401,
                    "headers": [(b"content-type", b"application/json"),
                                (b"www-authenticate", b"Bearer")],
                })
                await send({
                    "type": "http.response.body",
                    "body": b'{"error":"Missing or invalid bearer token."}',
                })
                return

            await self.app(scope, receive, send)

    return TokenAuthMiddleware

