"""Regression tests of the `modelDescription.xml` rewriting defects.

`FMU.apply_operation` rewrites the descriptor even for an operation that changes
nothing; that rewrite must keep the meaning of the document. Each test below
targets one defect listed in `docs/refactoring.md` (D1 to D9, D14). They were
written as `xfail(strict=True)` tests in phase 0 and pass since phase 2.
"""
import zipfile
from pathlib import Path

import pytest

from fmu_manipulation_toolbox.operations import FMU, OperationAbstract, OperationRemoveSources

from _helpers.assertions import assert_equivalent_xml

pytestmark = [pytest.mark.unit]

FMI2 = """<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription fmiVersion="2.0" modelName="m" guid="{{8c4e810f-3df3-4a00-8276-176fa3c9f000}}"{root_attrs}>
  <CoSimulation modelIdentifier="m">{cosimulation}</CoSimulation>
  {header}
  <ModelVariables>
    <ScalarVariable name="u" valueReference="1" causality="input" variability="continuous">
      <Real start="0"/>{variable}
    </ScalarVariable>
    <ScalarVariable name="y" valueReference="2" causality="output" variability="continuous">
      <Real/>
    </ScalarVariable>
  </ModelVariables>
  <ModelStructure>
    <Outputs><Unknown index="2" dependencies="1"/></Outputs>
  </ModelStructure>
</fmiModelDescription>
"""

FMI3 = """<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription fmiVersion="3.0" modelName="m" instantiationToken="{{8c4e810f-3df3-4a00-8276-176fa3c9f000}}">
  <CoSimulation modelIdentifier="m"/>
  <ModelVariables>
    <Float64 name="u" valueReference="1" causality="input" start="0">{variable}</Float64>
    <Float64 name="y" valueReference="2" causality="output"/>{extra_variable}
  </ModelVariables>
  <ModelStructure>
    <Output valueReference="2" dependencies="1"/>
  </ModelStructure>
</fmiModelDescription>
"""


def fmi2(root_attrs="", cosimulation="", header="", variable="") -> str:
    return FMI2.format(root_attrs=root_attrs, cosimulation=cosimulation, header=header, variable=variable)


def fmi3(variable="", extra_variable="") -> str:
    return FMI3.format(variable=variable, extra_variable=extra_variable)


def make_fmu(tmp_path: Path, descriptor: str, extra_files=()) -> Path:
    fmu_filename = tmp_path / "test.fmu"
    with zipfile.ZipFile(fmu_filename, "w") as fmu:
        fmu.writestr("modelDescription.xml", descriptor)
        for name in extra_files:
            fmu.writestr(name, "")
    return fmu_filename


def assert_noop_roundtrip(tmp_path: Path, descriptor: str, with_comments=False) -> None:
    fmu = FMU(str(make_fmu(tmp_path, descriptor)))
    fmu.apply_operation(OperationAbstract())
    assert_equivalent_xml(descriptor.encode("utf-8"), fmu.descriptor_filename, with_comments=with_comments)


# --------------------------------------------------------------------------- #
#                 Controls: the templates themselves round-trip                #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("descriptor", [fmi2(), fmi3()], ids=["fmi2", "fmi3"])
def test_plain_descriptor_roundtrip(tmp_path, descriptor):
    assert_noop_roundtrip(tmp_path, descriptor)


# --------------------------------------------------------------------------- #
#                                   Defects                                    #
# --------------------------------------------------------------------------- #
def test_d1_text_is_escaped(tmp_path):
    header = '<VendorAnnotations><Tool name="T"><Info>x &lt; y &amp; z</Info></Tool></VendorAnnotations>'
    assert_noop_roundtrip(tmp_path, fmi2(header=header))


def test_d2_string_start_is_escaped(tmp_path):
    extra = ('\n    <String name="s" valueReference="3" causality="parameter" variability="fixed">'
             '<Start value="a&quot;b&lt;c"/></String>')
    assert_noop_roundtrip(tmp_path, fmi3(extra_variable=extra))


def test_d3_attributes_are_not_unescaped_twice(tmp_path):
    assert_noop_roundtrip(tmp_path, fmi2(root_attrs=' description="a &amp;lt; b"'))


def test_d4_fmi2_variable_annotations_are_kept(tmp_path):
    variable = '\n      <Annotations><Tool name="T"><Meta k="v"/></Tool></Annotations>'
    assert_noop_roundtrip(tmp_path, fmi2(variable=variable))


def test_d4_fmi3_alias_is_kept(tmp_path):
    assert_noop_roundtrip(tmp_path, fmi3(variable='<Alias name="u_alias" description="alias"/>'))


def test_d4_fmi3_string_array_start_values_are_kept(tmp_path):
    extra = ('\n    <String name="s" valueReference="3" causality="parameter" variability="fixed">'
             '<Dimension start="2"/><Start value="a"/><Start value="b"/></String>')
    assert_noop_roundtrip(tmp_path, fmi3(extra_variable=extra))


def test_d5_comments_are_kept(tmp_path):
    assert_noop_roundtrip(tmp_path, fmi2(header="<!-- generated by hand -->"), with_comments=True)


def test_d5_xml_declaration_is_kept(tmp_path):
    fmu = FMU(str(make_fmu(tmp_path, fmi2())))
    fmu.apply_operation(OperationAbstract())
    assert Path(fmu.descriptor_filename).read_bytes().startswith(b"<?xml")


def test_d6_operations_can_be_chained(tmp_path):
    header = '<VendorAnnotations><Tool name="T"><Info>x &lt; y</Info></Tool></VendorAnnotations>'
    fmu = FMU(str(make_fmu(tmp_path, fmi2(header=header))))
    fmu.apply_operation(OperationAbstract())
    fmu.apply_operation(OperationAbstract())


def test_d9_remove_sources_updates_descriptor(tmp_path):
    cosimulation = '<SourceFiles><File name="m.c"/></SourceFiles>'
    fmu = FMU(str(make_fmu(tmp_path, fmi2(cosimulation=cosimulation), extra_files=["sources/m.c"])))
    fmu.apply_operation(OperationRemoveSources())
    assert not (Path(fmu.tmp_directory) / "sources").exists()
    assert b"SourceFiles" not in Path(fmu.descriptor_filename).read_bytes()


def test_d14_fmi3_empty_binary_start_is_kept(tmp_path):
    extra = ('\n    <Binary name="b" valueReference="3" causality="input" variability="discrete">'
             '<Start value=""/></Binary>')
    assert_noop_roundtrip(tmp_path, fmi3(extra_variable=extra))


def test_d14_fmi3_array_of_size_one_stays_an_array(tmp_path):
    extra = '\n    <Float64 name="a" valueReference="3" causality="input"><Dimension start="1"/></Float64>'
    assert_noop_roundtrip(tmp_path, fmi3(extra_variable=extra))
